apiVersion: v1
kind: Pod
metadata:
  name: nu-quickstart-customerservice
  labels:
    nu-quickstart: "sample"
    app: "customer-service"
spec:
  containers:
  - name: customer-service
    image: ghcr.io/touk/nussknacker-quickstart/customerservice:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5001
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    nu-quickstart: "sample"
spec:
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001        

