version: '3.7'

services:
  designer:
    container_name: nussknacker_designer
    image: ${NUSSKNACKER_IMAGE-touk/nussknacker}:${NUSSKNACKER_VERSION-staging-latest}
    ports:
      - "3081:8080"
    environment:
      #multiple, comma separated, config files can be used. They will be merged in order, via HOCON fallback mechanism
      #https://github.com/lightbend/config/blob/master/HOCON.md#config-object-merging-and-file-merging
      CONFIG_FILE: ${NUSSKNACKER_CONFIG_FILE-/opt/nussknacker/conf/application.conf,/opt/nussknacker/conf/nussknacker.conf}
      JDK_JAVA_OPTIONS: -Xmx256M
      FLINK_REST_URL: http://jobmanager:8081
      FLINK_QUERYABLE_STATE_PROXY_URL: taskmanager:9069
      KAFKA_ADDRESS: kafka:9092
      SCHEMA_REGISTRY_URL: http://schemaregistry:8081
      COUNTS_URL: http://influxdb:8086/query
      OPENAPI_SERVICE_URL: http://customerservice:5000
    volumes:
      - storage_designer:/opt/nussknacker/storage
      #this is needed to be able to verify savepoints during deployments
      - storage_flink:/opt/flink/data
      - ./nussknacker/nussknacker.conf:/opt/nussknacker/conf/nussknacker.conf
      - ~/.m2/repository/org/apache/ignite/ignite-core/2.10.0/ignite-core-2.10.0.jar:/opt/nussknacker/lib/ignite-core-2.10.0.jar
      - ~/.m2/repository/org/hsqldb/hsqldb/2.6.0/hsqldb-2.6.0.jar:/opt/nussknacker/lib/hsqldb-2.6.0.jar

  ignite:
    container_name: nussknacker_ignite
    image: apacheignite/ignite:${IGNITE_VERSION-2.10.0}
    ports:
      - 10800:10800
      - 9020:9020
    volumes:
      - ./ignite:/user_config
      - storage_ignite:/persistent_storage
    environment:
      - OPTION_LIBS=ignite-rest-http,ignite-indexing,ignite-zookeeper
      - IGNITE_WORK_DIR=/persistent_storage
      - CONFIG_URI=file:///user_config/ignite-config.xml

volumes:
  storage_designer:
    name: nussknacker_storage_designer
  storage_flink:
    name: nussknacker_storage_flink
  storage_ignite:
    name: nussknacker_storage_ignite

networks:
  default:
    name: nussknacker_network
