apiVersion: v1
kind: Pod
metadata:
  name: nu-quickstart-world-db
  labels:
    nu-quickstart: "sample"
    app: "world-db"
spec:
  containers:
  - name: db
    image: ghusta/postgres-world-db
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5432
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: world-db
  labels:
    nu-quickstart: "sample"
spec:
  selector:
    app: "world-db"
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Pod
metadata:
  name: nu-quickstart-customerservice
  labels:
    nu-quickstart: "sample"
    app: "customer-service"
spec:
  containers:
  - name: customer-service
    image: ghcr.io/touk/nussknacker-quickstart/customerservice:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5000
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    nu-quickstart: "sample"
spec:
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000        

