openapi: 3.0.0
info:
  title: Customer Profile API
  version: 1.0.0

paths:
  '/customer/{customerId}/profile':
    get:
      summary: Get customer profile by customer's ID
      description: Get customer profile information by customer's ID.
      operationId: getCustomerProfile
      parameters:
        - name: customerId
          in: path
          required: true
          description: Id of a customer.
          schema:
            type: integer
      responses:
        '200':
          description: Customer profile found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerProfile'
        '404':
          description: No customer profile found

components:
  schemas:
    CustomerProfile:
      title: CustomerProfile
      type: object
      properties:
        id:
          type: integer
          description: Profile's unique identifier.
        customerType:
          type: string
          description: Type of the customer.
