{
 "title": "Lite scenario",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "scenarioName",
    "query": "SHOW TAG VALUES FROM \"source.instantRate\" WITH KEY = \"scenario\""
   },
   {
    "name": "env",
    "query": "SHOW TAG VALUES FROM \"source.instantRate\" WITH KEY = \"env\""
   },
   {
    "name": "interval",
    "query": "10s,30s,1m,3m, 10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Basics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Source throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeId]]",
     "query": "SELECT sum(value)\nFROM (\n  SELECT non_negative_derivative(last(\"count\"), 1s) AS value\n  FROM \"source.count\"\n  WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), scenario, nodeId, taskId\n)\nGROUP BY time($__interval), scenario, nodeId\n"
    }
   ]
  },
  {
   "title": "Events that passed whole scenario /s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeId]]",
     "query": "SELECT sum(value)\nFROM (\n  SELECT non_negative_derivative(last(\"count\"), 1s) AS value\n  FROM \"end.count\"\n  WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), scenario, nodeId, taskId\n)\nGROUP BY time($__interval), scenario, nodeId\n"
    }
   ]
  },
  {
   "title": "Rejected events /s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeId]]",
     "query": "SELECT sum(value)\nFROM (\n  SELECT non_negative_derivative(last(\"count\"), 1s) AS value\n  FROM \"dead_end.count\"\n  WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), scenario, nodeId, taskId\n)\nGROUP BY time($__interval), scenario, nodeId\n"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeId]]",
     "query": "SELECT sum(value)\nFROM (\n  SELECT non_negative_derivative(last(\"count\"), 1s) AS value\n  FROM \"error.instantRateByNode.count\"\n  WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), scenario, nodeId, taskId\n)\nGROUP BY time($__interval), scenario, nodeId\n"
    }
   ]
  },
  {
   "title": "Max lag among Kafka source partitions (events)",
   "type": "graph",
   "description": "IMPORTANT. \nThis metric does NOT show the overall lag on Kafka source; a largest lag among all the source partitions is shown.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_operator_name]] (taskId [[tag_taskId]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "operator_name" ], "type": "tag" },
      { "params": [ "taskId" ], "type": "tag" }
     ],
     "measurement": "records-lag-max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/$scenarioName$/" }
     ]
    }
   ]
  },
  {
   "title": "Delay since event occurrence - minimum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeId]] (taskId [[tag_taskId]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "taskId" ], "type": "tag" },
      { "params": [ "nodeId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eventtimedelay.histogram",
     "select": [
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/$scenarioName$/" }
     ]
    }
   ]
  },
  {
   "title": "Delay since event occurrence - median",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeId]] (taskId [[tag_taskId]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "nodeId" ], "type": "tag" },
      { "params": [ "taskId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eventtimedelay.histogram",
     "select": [
      [
       { "params": [ "p50" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/$scenarioName$/" }
     ]
    }
   ]
  },
  {
   "title": "Delay since event occurrence - maximum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeId]] (taskId [[tag_taskId]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "taskId" ], "type": "tag" },
      { "params": [ "nodeId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eventtimedelay.histogram",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/$scenarioName$/" }
     ]
    }
   ]
  },
  {
   "title": "Time from latest event",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeId]] (taskId [[tag_taskId]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "nodeId" ], "type": "tag" },
      { "params": [ "taskId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eventtimedelay.minimalDelay",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/$scenarioName$/" }
     ]
    }
   ]
  },
  {
   "title": "External services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Services - median OK",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "[[tag_scenario]] - [[tag_serviceName]] (taskId [[tag_taskId]])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "scenario" ], "type": "tag" },
        { "params": [ "serviceName" ], "type": "tag" },
        { "params": [ "taskId" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "service.OK.histogram",
       "select": [
        [
         { "params": [ "p50" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
       ]
      }
     ]
    },
    {
     "title": "Services - 99th percentile OK",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "[[tag_scenario]] - [[tag_serviceName]] (taskId [[tag_taskId]])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "scenario" ], "type": "tag" },
        { "params": [ "serviceName" ], "type": "tag" },
        { "params": [ "taskId" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "service.OK.histogram",
       "select": [
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
       ]
      }
     ]
    },
    {
     "title": "Services - throughput OK",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "alias": "[[tag_scenario]] - [[tag_serviceName]]",
       "query": "SELECT sum(mean)\nFROM (\n  SELECT mean(value)\n  FROM \"service.OK.instantRate\"\n  WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), scenario, serviceName, taskId\n)\nGROUP BY time($__interval), scenario, serviceName"
      }
     ]
    },
    {
     "title": "Services - median FAIL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "[[tag_scenario]] - [[tag_serviceName]] (taskId [[tag_taskId]])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "scenario" ], "type": "tag" },
        { "params": [ "serviceName" ], "type": "tag" },
        { "params": [ "taskId" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "service.FAIL.histogram",
       "select": [
        [
         { "params": [ "p50" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
       ]
      }
     ]
    },
    {
     "title": "Services - 99th percentile FAIL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "[[tag_scenario]] - [[tag_serviceName]] (taskId [[tag_taskId]])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "scenario" ], "type": "tag" },
        { "params": [ "serviceName" ], "type": "tag" },
        { "params": [ "taskId" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "service.FAIL.histogram",
       "select": [
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
       ]
      }
     ]
    },
    {
     "title": "Services - throughput FAIL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "alias": "$tag_scenario - $tag_serviceName",
       "query": "SELECT sum(mean)\nFROM (\n  SELECT mean(value)\n  FROM \"service.FAIL.instantRate\"\n  WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), scenario, serviceName, taskId\n)\nGROUP BY time($__interval), scenario, serviceName"
      }
     ]
    }
   ]
  }
 ]
}