#!/bin/bash -e

cd "$(dirname "$0")"

if [ "$#" -ne 1 ]; then
    echo "Error: One parameter required: 1) scenario example folder path"
    exit 1
fi

function runRequestSending() {
  if [ "$#" -ne 2 ]; then
    echo "Error: Two parameters required: 1) OpenAPI service slug, 2) request generator script"
    exit 11
  fi

  set -e

  local OPENAPI_SERVICE_SLUG=$1
  local REQUEST_GENERATOR_SCRIPT=$2

  echo "Starting to send to '$OPENAPI_SERVICE_SLUG' OpenAPI service, requests generated by '$REQUEST_GENERATOR_SCRIPT' generator script"

  mkdir -p /var/log/continuously-send-http-requests
  nohup ../../utils/http/continuously-send-http-requests.sh "$OPENAPI_SERVICE_SLUG" "$REQUEST_GENERATOR_SCRIPT" > /var/log/continuously-send-http-requests/output.log 2>&1 &
}

SCENARIO_EXAMPLE_DIR_PATH=${1%/}

echo "Starting to send generated requests to Nu OpenAPI services ..."

shopt -s nullglob

for ITEM in "$SCENARIO_EXAMPLE_DIR_PATH/data/http/generated"/*; do
  if [ ! -f "$ITEM" ]; then
    continue
  fi

  if [[ ! "$ITEM" == *.sh ]]; then
    echo "Unrecognized file $ITEM. Required file with extension '.sh' and content with bash script"
    exit 3
  fi

  OPENAPI_SERVICE_SLUG=$(basename "$ITEM" ".sh")

  runRequestSending "$OPENAPI_SERVICE_SLUG" "$ITEM"

done

echo -e "DONE!\n\n"
