#!/bin/bash -ex

cd "$(dirname "$0")"

function runMessageSending() {
  if [ "$#" -ne 2 ]; then
    echo "Error: Two parameters required: 1) topic name, 2) message generator script"
    exit 11
  fi

  set -e

  local TOPIC_NAME=$1
  local MSG_GENERATOR_SCRIPT=$2

  echo "Startint to send to '$TOPIC_NAME' messages generated by '$MSG_GENERATOR_SCRIPT' generator script"
  nohup ../utils/kafka/continously-send-to-topic.sh "$TOPIC_NAME" "$MSG_GENERATOR_SCRIPT" > /dev/null &
}

echo "Starting to send preconfigured messages ..."

for FILE in "../../data/kafka/generate-messages"/*; do
  if [ -f "$FILE" ]; then
    TOPIC_NAME=$(basename "$FILE" .sh) 

    while IFS= read -r MSG; do
      if [[ $MSG == "#"* ]]; then
        continue
      fi

      runMessageSending "$TOPIC_NAME" "$(realpath $FILE)"
    done < "$FILE"
  fi
done

echo "DONE!"
