#!/bin/bash -ex

cd "$(dirname "$0")"

function runMessageSending() {
  if [ "$#" -ne 2 ]; then
    echo "Error: Two parameters required: 1) topic name, 2) message generator script"
    exit 11
  fi

  set -e

  local TOPIC_NAME=$1
  local MSG_GENERATOR_SCRIPT=$2

  echo "Starting to send to '$TOPIC_NAME' messages generated by '$MSG_GENERATOR_SCRIPT' generator script"

  mkdir -p /var/log/continuously-send-to-topic
  nohup ../utils/kafka/continuously-send-to-topic.sh "$TOPIC_NAME" "$MSG_GENERATOR_SCRIPT" > /var/log/continuously-send-to-topic/output.log 2>&1 &
}

echo "Starting to send generated messages ..."

while IFS= read -r TOPIC_NAME; do

  if [[ $TOPIC_NAME == "#"* ]]; then
    continue
  fi

  MSG_GENERATION_SCRIPT="../../data/kafka/generate-messages/$TOPIC_NAME.sh"

  if [[ -f "$MSG_GENERATION_SCRIPT" ]]; then
    runMessageSending "$TOPIC_NAME" "$(realpath $MSG_GENERATION_SCRIPT)"
  fi

done < "../../data/kafka/topics.txt"

echo "DONE!"
