#!/bin/bash -e

cd "$(dirname "$0")"

source ../../utils/lib.sh

if [ "$#" -ne 1 ]; then
    red_echo "ERROR: One parameter required: 1) scenario example folder path\n"
    exit 1
fi

function run_message_sending() {
  if [ "$#" -ne 2 ]; then
    red_echo "ERROR: Two parameters required: 1) topic name, 2) message generator script\n"
    exit 11
  fi

  set -e

  local TOPIC_NAME=$1
  local MSG_GENERATOR_SCRIPT=$2

  echo -n "Starting to send to '$TOPIC_NAME' messages generated by '$MSG_GENERATOR_SCRIPT' generator script... "

  mkdir -p /var/log/continuously-send-to-topic
  nohup ../../utils/kafka/continuously-send-to-topic.sh "$TOPIC_NAME" "$MSG_GENERATOR_SCRIPT" > /var/log/continuously-send-to-topic/output.log 2>&1 &

  echo "OK"
}

SCENARIO_EXAMPLE_DIR_PATH=${1%/}

echo "Starting to send generated messages..."

shopt -s nullglob

for ITEM in "$SCENARIO_EXAMPLE_DIR_PATH/data/kafka/generated"/*; do
  if [ ! -f "$ITEM" ]; then
    continue
  fi

  if [[ ! "$ITEM" == *.sh ]]; then
    red_echo "ERROR: Unrecognized file $ITEM. Required file with extension '.sh' and content with bash script\n"
    exit 3
  fi

  TOPIC_NAME=$(basename "$ITEM" ".sh" | sed 's/.*/\u&/')

  run_message_sending "$TOPIC_NAME" "$ITEM"

done

echo -e "Generators are running!\n"
