s/eventtimedelay_histogram/eventtimedelay.histogram/g
s/eventtimedelay_minimalDelay/eventtimedelay.minimalDelay/g
s/service_OK_histogram/service.OK.histogram/g
s/service_FAIL_histogram/service.FAIL.histogram/g
s/service_OK_instantRate/service.OK.instantRate/g
s/service_FAIL_instantRate/service.FAIL.instantRate/g
s/source_instantRate/source.instantRate/g
s/source_count/source.count/g
s/end_count/end.count/g
s/dead_end_count/dead_end.count/g
s/error_instantRateByNode_count/error.instantRateByNode.count/g
s/slot/taskId/g
