image:
  pullPolicy: Always

resources:
  limits:
    memory: 700Mi
  requests:
    memory: 256Mi

ingress:
  enabled: true
  skipHost: true
  #Change for other certs 
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

nussknacker:
  mode: "streaming-lite"
  #additional AKHQ tab
  customTabs: 
    - title: "Data"
      id: "data"
      url: "/akhq/ui/nussknacker/topic"
      type: "IFrame"
  modelConfig:
    components:
      openAPI:
        url: "http://customer-service/swagger"
        rootUrl: "http://customer-service"
    kafka:
      schemaRegistryCacheConfig:
        availableSchemasExpirationTime: "{{ .Values.kafka.schemaRegistryCacheConfig.availableSchemasExpirationTime }}"
  usageStatisticsReportsSource: "quickstart-helmchart"

persistence: 
  enabled: false      

#These are needed only for flink         
telegraf:
  enabled: false
flink:
  enabled: false

kafka:
  replicas: 1
  deleteTopicEnable: true

zookeeper:
  replicaCount: 1

extraEnv:
  - name: NUSSKNACKER_LOG_LEVEL
    value: INFO