name: Push customerservice

on:
  push:
    branches:
      - main
      - staging
      - release/*

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest
    env:
      VERSION:  ${{ (github.base_ref == 'staging' || github.ref_name == 'staging') && 'staging-latest' || 'latest' }}
      REGISTRY: ghcr.io
      IMAGE_NAME: touk/nussknacker-quickstart/customerservice
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.8.0
        with:
          context: ./common/customerservice
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ env.VERSION }}
