name: QUICKSTART CI

on:
  pull_request:
    branches:
      - main
      - staging
      - release/*
  push:
    branches:
      - main
      - staging
      - release/*

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Test Quickstart start
        timeout-minutes: 10
        run: |
          ./new-quickstart/run.sh || (docker-compose logs && exit 1) 
      - name: Clean up Quickstart
        run: |
          ./new-quickstart/stop-and-clean.sh 
  